apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        #- name: MYSQL_DATABASE
        #  value: "fbm_peliculas"
        #- name: MYSQL_USER
        #  valueFrom:
        #    secretKeyRef:
        #      name: mysql-secret
        #      key: username
        #- name: MYSQL_PASSWORD
        #  valueFrom:
        #    secretKeyRef:
        #      name: mysql-secret
        #      key: password
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        # Script sql de iniciación para crear las 2 bbdd
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      # Script sql de iniciación para crear las 2 bbdd
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
