-- authorities
INSERT INTO `` (`idRol`,`authority`) VALUES (1,'ROLE_ADMIN');
INSERT INTO `` (`idRol`,`authority`) VALUES (2,'ROLE_USER');
-- users
INSERT INTO `` (`idUsuario`,`username`,`password`,`correo`,`enable`) VALUES (3,'ismael','$2a$10$ui2GtONthkWsyeEcakTYC.uo4cohC0l1uzanJK0CeWJBhaM7CaVqG','ismael@gmail.com',1);
INSERT INTO `` (`idUsuario`,`username`,`password`,`correo`,`enable`) VALUES (4,'juan','$2a$10$ui2GtONthkWsyeEcakTYC.uo4cohC0l1uzanJK0CeWJBhaM7CaVqG','juan@gmail.com',1);
INSERT INTO `` (`idUsuario`,`username`,`password`,`correo`,`enable`) VALUES (5,'antonio','$2a$10$ui2GtONthkWsyeEcakTYC.uo4cohC0l1uzanJK0CeWJBhaM7CaVqG','antonio@gmail.com',1);
INSERT INTO `` (`idUsuario`,`username`,`password`,`correo`,`enable`) VALUES (6,'admin','$2a$10$ui2GtONthkWsyeEcakTYC.uo4cohC0l1uzanJK0CeWJBhaM7CaVqG','admin@gmail.com',1);
INSERT INTO `` (`idUsuario`,`username`,`password`,`correo`,`enable`) VALUES (8,'jose','$2a$10$ui2GtONthkWsyeEcakTYC.uo4cohC0l1uzanJK0CeWJBhaM7CaVqG','jose@gmail.com',1);
-- users_has_authorities
INSERT INTO `` (`idUsuario`,`idRol`) VALUES (3,1);
INSERT INTO `` (`idUsuario`,`idRol`) VALUES (6,1);
INSERT INTO `` (`idUsuario`,`idRol`) VALUES (3,2);
INSERT INTO `` (`idUsuario`,`idRol`) VALUES (4,2);
INSERT INTO `` (`idUsuario`,`idRol`) VALUES (5,2);
INSERT INTO `` (`idUsuario`,`idRol`) VALUES (8,2);
-- criticas
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (1,7,'Muy buena pelicula nfgsdklfjpoaskefjsaodjkfsdlkjfsd\r\nklñsfadjfas\r\nsdkljfpoasdkjfposdakjfdkfasdf\r\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',8,'2024-12-20',3);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (2,7,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas diam eros, porttitor sit amet aliquam convallis, posuere quis odio. Mauris egestas justo id quam cursus, eu semper magna fringilla. In dui elit, egestas vitae scelerisque ut, condimentum a enim. Sed efficitur ipsum ac imperdiet aliquam. Sed ut fermentum dui, vitae porta sem. Mauris vitae lorem sed libero dignissim consequat. Curabitur aliquam, est in egestas condimentum, sapien magna tincidunt nulla, ac gravida nulla leo ac dolor. Cras lacinia vel ligula ac convallis. Donec imperdiet ex in augue pretium posuere. Donec ultricies maximus augue, eget molestie nisi tincidunt ut. Maecenas ornare, dolor nec finibus porttitor, ex lectus vehicula urna, nec ullamcorper diam sem et dui.\r\n\r\nCurabitur condimentum ultrices mollis. Vestibulum nibh magna, semper vel finibus sed, pretium quis felis. Quisque nec enim nec mauris convallis vestibulum. Suspendisse sodales eu tellus a molestie. Nam porta sollicitudin bibendum. Sed varius justo ac diam mollis, at lacinia lorem viverra. Ut sit amet elit metus. Integer hendrerit commodo egestas. Phasellus a viverra nisi, a laoreet libero. Fusce dictum, lectus auctor iaculis mattis, arcu tortor scelerisque magna, ac vehicula leo metus nec neque. Proin ut justo vel ipsum pretium faucibus at vitae mi. In lectus orci, facilisis a rutrum vitae, sodales varius augue. Curabitur vitae tempor odio.',3,'2025-01-25',5);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (6,13,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc rhoncus posuere justo at tempor. Vivamus porta tristique felis, sed scelerisque purus rhoncus et. Integer mollis tellus eget lectus consectetur, sed efficitur ligula finibus. Cras maximus justo non mollis ultrices. Donec bibendum tellus velit, nec rhoncus odio ullamcorper ut. Maecenas luctus ultrices mi. Quisque consequat vulputate dolor.',8,'2024-12-26',3);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (9,4,'Una obra maestra del cine de fantasía. La ambientación, la música y la fidelidad al libro son impresionantes. Un inicio perfecto para la trilogía.',10,'2025-02-08',5);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (10,5,'Mejor que la primera en cuanto a ritmo y batallas. La batalla del Abismo de Helm es espectacular y Gollum es un personaje brillante.',10,'2025-02-08',5);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (11,6,'Un cierre épico y emotivo para la mejor trilogía de la historia del cine. La batalla final es simplemente perfecta.',10,'2025-02-08',5);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (12,14,'Entretenida y con grandes momentos, aunque se nota que alargaron la historia más de lo necesario. Martin Freeman es un excelente Bilbo.',7,'2025-02-08',5);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (13,4,'Visualmente impresionante, aunque algo lenta en algunos tramos. Sin embargo, la historia y los personajes están increíblemente bien desarrollados.',8,'2025-02-08',3);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (14,5,'Más oscura y épica, aunque se siente como una película de transición. Aun así, la evolución de los personajes es notable.',8,'2025-02-08',3);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (15,6,'Demasiados finales alargados, pero cada uno de ellos es merecido. El clímax de la historia es inolvidable.',9,'2025-02-08',3);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (16,14,'Visualmente hermosa, pero le falta el tono épico de El Señor de los Anillos. Aun así, la aventura es muy disfrutable.',8,'2025-02-08',3);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (17,4,'Peter Jackson logró lo imposible: trasladar la magia de Tolkien a la gran pantalla. La banda sonora de Howard Shore es sublime.',9,'2025-02-08',4);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (18,5,'Los efectos especiales han envejecido bien, y la historia mantiene la emoción. Gollum se roba la pantalla con su complejidad.',9,'2025-02-08',4);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (19,6,'Acción, emoción y un desenlace espectacular. Es difícil no soltar una lágrima en las escenas finales.',10,'2025-02-08',4);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (20,14,'El inicio es lento, pero cuando llega la acción se vuelve muy emocionante. La escena de los acertijos con Gollum es fantástica.',8,'2025-02-08',4);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (21,4,'El viaje de Frodo y la Compañía es fascinante, aunque el exceso de diálogos ralentiza el ritmo en algunas partes.',7,'2025-02-08',8);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (22,5,'Aunque la trama se divide en varias historias, todas son emocionantes. La tensión se mantiene constante y los nuevos personajes son geniales.',9,'2025-02-08',8);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (23,6,'La carga emocional es enorme. Frodo, Sam y Gollum tienen uno de los mejores arcos narrativos jamás creados.',10,'2025-02-08',8);
INSERT INTO `` (`idCritica`,`idPelicula`,`valoracion`,`nota`,`fecha`,`idUsuario`) VALUES (24,14,'Más ligera y humorística que la trilogía original, lo cual es un punto positivo para algunos y negativo para otros. Aun así, es una gran aventura.',7,'2025-02-08',8);
