apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-vs
spec:
  hosts:
  - "*"
  gateways:
  - app-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: frontend.default.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: peliculas-backend-vs
spec:
  hosts:
  - peliculas-backend.default.svc.cluster.local
  http:
  - match:
    - headers:
        X-Version:
          exact: "v1"
    route:
    - destination:
        host: peliculas-backend.default.svc.cluster.local
        subset: v1
        port:
          number: 8001
  - match:
    - headers:
        X-Version:
          exact: "v2"
    route:
    - destination:
        host: peliculas-backend.default.svc.cluster.local
        subset: v2
        port:
          number: 8001
  - route:
    # En caso de que no se envíe la cabecera, balance de carga entre las versiones
    - destination:
        host: peliculas-backend.default.svc.cluster.local
        subset: v1
        port:
          number: 8001
      weight: 100
    - destination:
        host: peliculas-backend.default.svc.cluster.local
        subset: v2
        port:
          number: 8001
      weight: 0
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: usuarios-backend-vs
spec:
  hosts:
  - usuarios-backend.default.svc.cluster.local
  http:
  - match:
    - headers:
        X-Version:
          exact: "v1"
    route:
    - destination:
        host: usuarios-backend.default.svc.cluster.local
        subset: v1
        port:
          number: 8002
  - match:
    - headers:
        X-Version:
          exact: "v2"
    route:
    - destination:
        host: usuarios-backend.default.svc.cluster.local
        subset: v2
        port:
          number: 8002
  - route:
    # En caso de que no se envíe la cabecera, balance de carga entre las versiones
    - destination:
        host: usuarios-backend.default.svc.cluster.local
        subset: v1
        port:
          number: 8002
      weight: 100
    - destination:
        host: usuarios-backend.default.svc.cluster.local
        subset: v2
        port:
          number: 8002
      weight: 0
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: password-generator-backend-vs
spec:
  hosts:
  - password-generator-backend.default.svc.cluster.local
  http:
  - match:
    - headers:
        X-Version:
          exact: "v1"
    route:
    - destination:
        host: password-generator-backend.default.svc.cluster.local
        subset: v1
        port:
          number: 8004
  - match:
    - headers:
        X-Version:
          exact: "v2"
    route:
    - destination:
        host: password-generator-backend.default.svc.cluster.local
        subset: v2
        port:
          number: 8004
  - route:
    # En caso de que no se envíe la cabecera, balance de carga entre las versiones
    - destination:
        host: password-generator-backend.default.svc.cluster.local
        subset: v1
        port:
          number: 8004
      weight: 100
    - destination:
        host: password-generator-backend.default.svc.cluster.local
        subset: v2
        port:
          number: 8004
      weight: 0
