apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator-backend-v1
  labels:
    app: password-generator-backend
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: password-generator-backend
      version: v1
  template:
    metadata:
      labels:
        app: password-generator-backend
        version: v1
    spec:
      containers:
      - name: password-generator-backend
        image: ismabc4/password_generator_backend:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8004
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator-backend-v2
  labels:
    app: password-generator-backend
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: password-generator-backend
      version: v2
  template:
    metadata:
      labels:
        app: password-generator-backend
        version: v2
    spec:
      containers:
      - name: password-generator-backend
        image: ismabc4/password_generator_backend:0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8004
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
