apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: password-generator-backend
  template:
    metadata:
      labels:
        app: password-generator-backend
    spec:
      containers:
      - name: password-generator-backend
        image: ismabc4/password_generator_backend:0.1
        ports:
        - containerPort: 8004
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
