apiVersion: apps/v1
kind: Deployment
metadata:
  name: peliculas-backend-v1
  labels:
    app: peliculas-backend
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: peliculas-backend
      version: v1
  template:
    metadata:
      labels:
        app: peliculas-backend
        version: v1
    spec:
      containers:
      - name: peliculas-backend
        image: ismabc4/peliculas_backend:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql.default.svc.cluster.local:3306/fbm_peliculas?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "4mysqlIsmaPassword_"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peliculas-backend-v2
  labels:
    app: peliculas-backend
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: peliculas-backend
      version: v2
  template:
    metadata:
      labels:
        app: peliculas-backend
        version: v2
    spec:
      containers:
      - name: peliculas-backend
        image: ismabc4/peliculas_backend:0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql.default.svc.cluster.local:3306/fbm_peliculas?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "4mysqlIsmaPassword_"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
