apiVersion: v1
kind: Service
metadata:
  name: password-generator-backend
spec:
  selector:
    app: password-generator-backend
  ports:
  - protocol: TCP
    port: 8004
    targetPort: 8004
  type: ClusterIP
