apiVersion: v1
kind: Service
metadata:
  name: peliculas-backend
spec:
  selector:
    app: peliculas-backend
  ports:
  - name: http
    protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP
