apiVersion: v1
kind: Service
metadata:
  name: usuarios-backend
spec:
  selector:
    app: usuarios-backend
  ports:
  - name: http
    protocol: TCP
    port: 8002
    targetPort: 8002
  type: ClusterIP
